import React from 'react'

const Progress = () => {
  return (
    <section id="progress" className="section">
        <div className="row mb-4">
          <div className="col-12">
            <h2 className="fw-bold">Learning Progress</h2>
            <p className="text-muted">Your statistics and achievements.</p>
          </div>
        </div>

        <div className="row mb-4">
          <div className="col-md-8 mb-4">
            <div className="card h-100 shadow-sm">
              <div className="card-header bg-white py-3">
                <h5 className="mb-0 fw-bold">Mastery Distribution</h5>
              </div>
              <div className="card-body">
                <canvas id="masteryChart" height="280"></canvas>
              </div>
            </div>
          </div>
          <div className="col-md-4 mb-4">
            <div className="card h-100 shadow-sm">
              <div className="card-header bg-white py-3">
                <h5 className="mb-0 fw-bold">Achievements</h5>
              </div>
              <div className="card-body">
                <div className="text-center mb-4">
                  <div className="display-4 text-warning mb-2">
                    <i className="fas fa-award"></i>
                  </div>
                  <h4 className="fw-bold" id="achievementCount">0 Earned</h4>
                </div>
                <div id="achievementsList" className="list-group list-group-flush">
                  {/* <!-- Achievements generated by JS --> */}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="row">
          <div className="col-md-6 mb-4">
            <div className="card h-100 shadow-sm">
              <div className="card-header bg-white py-3">
                <h5 className="mb-0 fw-bold">Study Activity</h5>
              </div>
              <div className="card-body">
                <div className="row g-4">
                  <div className="col-6">
                    <div className="p-3 bg-light rounded-3 text-center">
                      <h3 className="fw-bold mb-0" id="totalStudyTime">0</h3>
                      <small className="text-muted">Minutes</small>
                    </div>
                  </div>
                  <div className="col-6">
                    <div className="p-3 bg-light rounded-3 text-center">
                      <h3 className="fw-bold mb-0" id="totalCardsReviewed">0</h3>
                      <small className="text-muted">Cards</small>
                    </div>
                  </div>
                  <div className="col-6">
                    <div className="p-3 bg-light rounded-3 text-center">
                      <h3 className="fw-bold mb-0" id="totalQuizzesTaken">0</h3>
                      <small className="text-muted">Quizzes</small>
                    </div>
                  </div>
                  <div className="col-6">
                    <div className="p-3 bg-light rounded-3 text-center">
                      <h3 className="fw-bold mb-0" id="averageQuizScore">0%</h3>
                      <small className="text-muted">Avg Score</small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-md-6 mb-4">
            <div className="card h-100 shadow-sm">
              <div className="card-header bg-white py-3">
                <h5 className="mb-0 fw-bold">Tools & Export</h5>
              </div>
              <div className="card-body">
                <div className="d-grid gap-3">
                  <button
                    className="btn btn-outline-primary py-2"
                    id="exportBookmarks"
                  >
                    <i className="fas fa-download me-2"></i>Download Bookmarks
                  </button>
                  <button
                    className="btn btn-outline-success py-2"
                    id="exportMastered"
                  >
                    <i className="fas fa-file-export me-2"></i>Export Mastered Words
                  </button>
                  <button
                    className="btn btn-outline-info py-2"
                    id="printFlashcards"
                  >
                    <i className="fas fa-print me-2"></i>Print Study Set
                  </button>
                </div>
                <div
                  className="mt-4 p-3 bg-primary bg-opacity-10 rounded-3 border border-primary border-opacity-25"
                >
                  <h6 className="fw-bold text-primary mb-1">Daily Streak</h6>
                  <div className="d-flex align-items-center gap-3">
                    <h2 className="fw-bold mb-0" id="studyStreak">0</h2>
                    <p className="small text-muted mb-0">
                      Keep it up! Study every day to build your streak.
                    </p>
                  </div>
                  <div
                    id="streakCalendar"
                    className="d-flex gap-1 mt-3 overflow-auto pb-2"
                  ></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
  )
}

export default Progress
